-- both test users have the password "password"

INSERT INTO users (username, password, first_name, last_name, email, is_admin)
VALUES ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'User',
        'joel@joelburton.com',
        FALSE),
       ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'Admin!',
        'joel@joelburton.com',
        TRUE);

INSERT INTO products (name, price, currency, image)
VALUES  ('Blackwing Gift Set', 
        7200, 
        'USD', 
        '/products/blackwing-gift-set.png'),
        ('Spa Gift Set', 
        4000, 
        'USD', 
        '/products/spa-gift-set.png'),
        ('Map Paperweight', 
        8500, 
        'USD', 
        '/products/map-paperweight.png'),
        ('Basic Tee (Sienna)',
        3200,
        'USD',
        '/products/basic-tee-sienna.jpeg'),
       ('Basic Tee (Black)',
        3200,
        'USD',
        '/products/basic-tee-black.jpeg'),
       ('Nomad Tumbler',
       3500,
       'USD',
       '/products/nomad-tumbler.jpeg'),
       ('Artwork Tee',
       3200,
       'USD',
       '/products/artwork-tee.jpeg'),
       ('Henry',
       100000000,
       'USD',
       '/products/henry.png'),
       ('Mini Sketchbook Set',
       2800,
       'USD',
       '/products/mini-sketchbook-set.jpeg'),
       ('Organize Set',
       14900,
       'USD',
       '/products/organize-set.jpeg'),
       ('Machined Pen & Pencil',
       7000,
       'USD',
       '/products/machine-pen-pencil-set.jpeg'),
       ('Billfold Wallet',
       11800,
       'USD',
       '/products/billfold-wallet.jpeg');


INSERT INTO transactions (user_id, product_id, quantity, total_price)
VALUES
  ('testuser', 1, 2, 3200),
  ('testuser', 2, 1, 3200),
  ('testuser', 3, 3, 3500),
  ('testuser', 4, 1, 3200), 
  ('testadmin', 1, 2, 3200),
  ('testadmin', 3, 3, 3500);


